import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Cookies
import { cookies } from "next/headers";

// Themes
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();

  const res = await fetch("http://localhost:4000/api/auth/", {
    method: "GET",
    headers: {
      cookie: cookieStore.toString(), // forward session cookie to backend
    },
    cache: "no-store",
  });

  if (!res.ok) redirect("/login");

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            {/* <AppSidebar /> */}
            <main className="h-full w-full">
              {/* <SidebarTrigger /> */}
              <div className="min-h-screen w-full grow overflow-auto p-8">
                {children}
              </div>
            </main>
          </SidebarProvider>
          {/* <div className="bg-background flex h-full min-h-screen max-w-screen select-none">
            
          </div> */}
        </ThemeProvider>
        <Toaster position="top-center" theme="light" />
      </body>
    </html>
  );
}
